RubricaTelefonica/RubricaTelefonica/Controllers/ContattiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RubricaTelefonica.Models;

namespace RubricaTelefonica.Controllers
{
    public class ContattiController : Controller
    {
        private rubricaEntities db = new rubricaEntities();

        // GET: Contatti
        public ActionResult Index()
        {
            var contatto = db.contatto.Include(c => c.categoria);
            return View(contatto.OrderBy(c => c.cognome).ToList());
        }

        // GET: Contatti/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contatto contatto = db.contatto.Find(id);
            if (contatto == null)
            {
                return HttpNotFound();
            }
            return View(contatto);
        }

        // GET: Contatti/Create
        public ActionResult Create()
        {
            ViewBag.id_categoria = new SelectList(db.categoria, "id", "nome");
            return View();
        }

        // POST: Contatti/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,nome,cognome,telefono,email,indirizzo,foto,data_nascita,preferito,id_categoria")] contatto contatto)
        {
            if (ModelState.IsValid)
            {
                db.contatto.Add(contatto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_categoria = new SelectList(db.categoria, "id", "nome", contatto.id_categoria);
            return View(contatto);
        }

        // GET: Contatti/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contatto contatto = db.contatto.Find(id);
            if (contatto == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_categoria = new SelectList(db.categoria, "id", "nome", contatto.id_categoria);
            return View(contatto);
        }

        // POST: Contatti/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nome,cognome,telefono,email,indirizzo,foto,data_nascita,preferito,id_categoria")] contatto contatto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contatto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_categoria = new SelectList(db.categoria, "id", "nome", contatto.id_categoria);
            return View(contatto);
        }

        // GET: Contatti/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contatto contatto = db.contatto.Find(id);
            if (contatto == null)
            {
                return HttpNotFound();
            }
            return View(contatto);
        }

        // POST: Contatti/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            contatto contatto = db.contatto.Find(id);
            db.contatto.Remove(contatto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RubricaTelefonica/RubricaTelefonica/Views/Contatti/Create.cshtml
@model RubricaTelefonica.Models.contatto

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>contatto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cognome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cognome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cognome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.indirizzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.indirizzo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.indirizzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.foto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.data_nascita, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.data_nascita, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data_nascita, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.preferito, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.preferito)
                    @Html.ValidationMessageFor(model => model.preferito, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_categoria, "id_categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_categoria", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RubricaTelefonica/RubricaTelefonica/Views/Contatti/Delete.cshtml
@model RubricaTelefonica.Models.contatto

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>contatto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cognome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cognome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.indirizzo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.indirizzo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.data_nascita)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data_nascita)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.preferito)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.preferito)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoria.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoria.nome)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RubricaTelefonica/RubricaTelefonica/Views/Contatti/Details.cshtml
@model RubricaTelefonica.Models.contatto

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>contatto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cognome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cognome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.indirizzo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.indirizzo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.data_nascita)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data_nascita)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.preferito)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.preferito)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoria.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoria.nome)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RubricaTelefonica/RubricaTelefonica/Views/Contatti/Edit.cshtml
@model RubricaTelefonica.Models.contatto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>contatto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cognome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cognome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cognome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.indirizzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.indirizzo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.indirizzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.foto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.data_nascita, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.data_nascita, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data_nascita, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.preferito, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.preferito)
                    @Html.ValidationMessageFor(model => model.preferito, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_categoria, "id_categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_categoria", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RubricaTelefonica/RubricaTelefonica/Views/Contatti/Index.cshtml
@model IEnumerable<RubricaTelefonica.Models.contatto>

@{
    ViewBag.Title = "Index";
}

<h2>I miei contatti</h2>

<p>
    @Html.ActionLink("Nuovo contatto", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Cognome
        </th>
        <th>
            Nome
        </th>
        <th>
            Telefono
        </th>
        <th>
            E-mail
        </th>
        <th>
            Indirizzo
        </th>
        <th>
            Data di nascita
        </th>
        <th>
            Preferito
        </th>
        <th>
            Categoria
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.cognome)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.nome)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.telefono)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.indirizzo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.data_nascita)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.preferito)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.categoria.nome)
    </td>
    <td>
        <a href="@Url.Action("Edit", "Contatti", new { id=item.id })" class="btn btn-primary">Modifica</a>
        <a href="@Url.Action("Details", "Contatti", new { id=item.id })" class="btn btn-primary">Dettagli</a>
        <a href="@Url.Action("Delete", "Contatti", new { id=item.id })" class="btn btn-primary">Elimina</a>
    </td>
</tr>
}

</table>